name: openyield
channels:
  - vlsida-eda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - boost-cpp=1.70.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - certifi=2025.1.31
  - cffi=1.17.1
  - contourpy=1.3.0
  - cycler=0.12.1
  - fftw=3.3.10
  - fonttools=4.56.0
  - freetype=2.12.1
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - gmp=6.3.0
  - hdf5=1.14.3
  - icu=64.2
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.12
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libaec=1.1.3
  - libamd=3.3.3
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcblas=3.9.0
  - libccolamd=3.3.4
  - libcholmod=5.3.1
  - libcolamd=3.3.4
  - libcurl=8.8.0
  - libcxsparse=4.4.1
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libjpeg-turbo=2.1.4
  - libklu=2.3.5
  - liblapack=3.9.0
  - libldl=3.3.2
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libparu=1.0.0
  - libpng=1.6.43
  - librbio=4.3.4
  - libspex=3.2.3
  - libspqr=4.3.4
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsuitesparseconfig=7.10.1
  - libtiff=4.2.0
  - libumfpack=6.3.5
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - matplotlib-base=3.9.4
  - metis=5.1.0
  - mpfr=4.2.1
  - mpi=1.0.1
  - mpich=4.2.3
  - munkres=1.1.4
  - ncurses=6.5
  - ngspice=41
  - ngspice-exe=41
  - ngspice-lib=41
  - numpy=1.26.4
  - olefile=0.47
  - openjpeg=2.4.0
  - openssl=3.5.0
  - packaging=24.2
  - pillow=8.2.0
  - pip=25.0.1
  - ply=3.11
  - pthread-stubs=0.4
  - pycparser=2.22
  - pyparsing=3.2.1
  - pyspice=1.5
  - python=3.9.19
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pyyaml=6.0.2
  - qhull=2020.2
  - readline=8.2
  - scikit-umfpack=0.3.3
  - scipy=1.13.1
  - setuptools=75.8.0
  - six=1.17.0
  - suitesparse=5.10.1
  - tbb=2022.0.0
  - tk=8.6.13
  - trilinos=12.18.1
  - unicodedata2=16.0.0
  - wheel=0.45.1
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxaw=1.0.16
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxmu=1.2.1
  - xorg-libxpm=3.5.17
  - xorg-libxt=1.3.1
  - xyce=7.4
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - charset-normalizer==3.4.1
      - deprecation==2.1.0
      - future==1.0.0
      - hierplace==1.1.0
      - idna==3.10
      - kinet2pcb==1.1.2
      - kinparse==1.2.3
      - pandas==2.2.3
      - python-graphviz==0.20.3
      - pytz==2025.1
      - requests==2.32.3
      - schemdraw==0.19
      - sexpdata==1.0.0
      - skidl==2.0.1
      - svgwrite==1.4.3
      - tzdata==2025.1
      - urllib3==2.3.0